version: "3"

services:
  mysqldb:
    container_name: mysql_Devops
    image: mysql
    restart: on_failure
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: tpachato
      MYSQL_ROOT_PASSWORD: root
  app:
    depends_on:
      - mysqldb
    image: anismoalla/devops
    restart: on_failure
    ports:
      - 8089:8089
    environment:
      MYSQL_HOST: mysql_Devops
      MYSQL_USER: root
      MYSQL_PASSWORD: root
