version: "3"

services:
  mysqldb:
    container_name: database
    image: mysql
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ROOT_PASSWORD: 123456
  app:
    depends_on:
      - mysqldb
    image: wissemellafi/devops
    ports:
      - 8089:8089
    environment:
      spring.datasource.url: jdbc:mysql://mysqldb:3306/achatdb
      spring.datasource.username: root
      spring.datasource.password: 123456
volumes:
  db:
