version: "3"

services:
  mysqldb:
    container_name: mysqlCICD
    image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: tpachato
      MYSQL_ROOT_PASSWORD: achat
  app:
    depends_on:
      - mysqldb
    image: wissemellafi/devops
    restart: always
    ports:
      - 8089:8089
    environment:
      MYSQL_HOST: mysqlCICD
      MYSQL_USER: root
      MYSQL_PASSWORD: achat
volumes:
  db:
