
version: "3"

services: 
  mysqldb:
    container_name: mysqldb
    environment: 
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      
    expose:
      - "3306"
    image: "mysql:5.7"
    ports: 
      - "3306:3306"
    restart: always
    volumes: 
      - "my-db:/var/lib/mysql"

  achatproject: 
   image: achrafab/achrafback:1.0.0
   container_name: achat
   restart: on-failure
   ports: 
    - 8089:8089
   depends_on:
    - mysqldb
volumes:
  my-db: ~